name: loco_app_widgetbook
description: Catalog of widgets.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.0.0
  provider: ^6.0.0
  mocktail: ^1.0.0 # Weird seen as a dependency and not a dev_dependency, but the whole app is a dev app.
  loco_app:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
